// Barrel re-export — all existing imports from '@/lib/types' continue to work
export * from './kanban'
export * from './tags'
export * from './shared'
export * from './routines'
export * from './habits'
export * from './goals'
export * from './journal'
export * from './focus'
export * from './dashboard'
